# Generated by Django 5.2.7 on 2025-10-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vistor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('phone_number', models.JSONField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_in', models.DateTimeField(blank=True, null=True)),
                ('signed_out', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
