# Generated by Django 5.2.7 on 2025-11-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reciept_id',
            new_name='receipt_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('security', 'Security'), ('resident', 'Resident')], default='resident', max_length=20),
        ),
    ]
