# Generated by Django 5.2.7 on 2025-12-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_visitor_alter_user_receipt_id_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('security', 'Security'), ('resident', 'Resident')], default='resident', max_length=20),
        ),
    ]
